# Generated by Django 2.2.2 on 2019-06-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_num', models.IntegerField()),
                ('author_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_num', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('book_name', models.CharField(max_length=100)),
                ('book_context', models.CharField(max_length=1000)),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Author')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Category')),
            ],
        ),
    ]
