# Generated by Django 2.1.7 on 2019-07-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_num',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_num',
        ),
    ]
